INSERT INTO parks (title, "location")
  VALUES ('Zion', 'Utah'),
         ('Grand Canyon', 'Arizona'),
         ('Denali', 'Alaska'),
         ('Acadia', 'Maine'),
         ('Yellowstone', 'Wyoming'),
         ('Olympic', 'Washington'),
         ('Gates of the Arctic', 'Alaska'),
         ('Rocky Mountain', 'Colorado'),
         ('Joshua Tree', 'California'),
         ('Gateway Arch', 'Missouri');
         

INSERT INTO lists (title, username)
  VALUES ('all', 'admin'),
         ('wishlist', 'admin'),
         ('visited', 'admin'),
         ('favorites', 'admin'),
         ('all', 'new_user'),
         ('wishlist', 'new_user'),
         ('visited', 'new_user');
        
INSERT INTO lists_parks (list_id, park_id)
  VALUES (1, 1),
         (1, 2),
         (1, 3),
         (1, 4),
         (1, 5),
         (1, 6),
         (1, 7),
         (1, 8),
         (1, 9),
         (1,10),
         (2, 6),
         (2, 8),
         (3, 9),
         (3, 2),
         (3, 3),
         (3, 4),
         (3, 5),
         (3, 7),
         (3, 10),
         (4, 6),
         (5, 1),
         (5, 2),
         (5, 3),
         (5, 4),
         (5, 5),
         (5, 6),
         (5, 7),
         (5, 8),
         (5, 9),
         (5,10);

-- INSERT INTO users_parksettings (username, park_id)
--   VALUES ('admin', 1),
--          ('admin', 2),
--          ('admin', 3),
--          ('admin', 4),
--          ('admin', 5),
--          ('admin', 6),
--          ('admin', 7),
--          ('admin', 8),
--          ('admin', 9),
--          ('admin', 10),
--          ('new_user', 1),
--          ('new_user', 2),
--          ('new_user', 3),
--          ('new_user', 4),
--          ('new_user', 5),
--          ('new_user', 6),
--          ('new_user', 7),
--          ('new_user', 8),
--          ('new_user', 9),
--          ('new_user', 10);
INSERT INTO users_parksettings (username, park_id, rating, notes)
  VALUES ('admin', 1, 5, 'Very cool!'),
         ('admin', 2, 5, 'Wow!'),
         ('admin', 3, 4, NULL),
         ('admin', 4, 5,  'I want to check out more of the trails next time'),
         ('admin', 5, 4, 'Great views, very crowded'),
         ('admin', 6, NULL, NULL),
         ('admin', 7, 3, NULL),
         ('admin', 8, NULL, NULL),
         ('admin', 9, NULL, NULL),
         ('admin', 10, 2, 'A little underwhelming compared to the others'),
         ('new_user', 1, NULL, NULL),
         ('new_user', 2, NULL, NULL),
         ('new_user', 3, NULL, NULL),
         ('new_user', 4, NULL, NULL),
         ('new_user', 5, NULL, NULL),
         ('new_user', 6, NULL, NULL),
         ('new_user', 7, NULL, NULL),
         ('new_user', 8, NULL, NULL),
         ('new_user', 9, NULL, NULL),
         ('new_user', 10, NULL, NULL);
